### ISSUE TITLE
The result files do not open

### ISSUE THREAD

**Issue by aravsekar** [frenkowski/SCIMAI-Gym#1]
Hello!

Great paper!
Am trying to replicate the paper with the codes that you have provided. To compare the results I am trying to look at your Results zip file and none of them open correctly. It says ' The file is invalid'. Can you please check on this? Thank you!

**Comment by frenkowski** [comment]
Hi @aravsekar,
I tried to download and open the zip files, and I had no problems! 
To grant you access to the results without difficulties, I uploaded the unzipped files on [Dropbox](https://www.dropbox.com/sh/bi610b3ajpgg3uc/AABTMyG_FitVpXajVcZmFrbKa?dl=0). 
If necessary, feel free to reopen the issue 🙂

**Comment by aravsekar** [comment]
Thank you so much! One thing that I am trying to replicate is the scenario for 1P and 3W. Can you please identify the spots where change needs to be made? 

![Screenshot 2022-09-22 195435](https://user-images.githubusercontent.com/91839158/191870694-2632785b-ebee-44eb-9253-ce4e65aa1a2d.png)
