### ISSUE TITLE
Ray Version - Complexities

### ISSUE THREAD

**Issue by aravsekar** [frenkowski/SCIMAI-Gym#2]
Hello

Have been able to replicate the exact scenarios that you have mentioned in the paper. One question that I would like to ask, is were you able to try the same model with more complexities involved such as n number of warehouses/products? The reason I ask is the Ray version fails as more complexities get into the picture. Have you tried that? Wanted your opinions on it. Thank you so much!

**Comment by frenkowski** [comment]
Hi @aravsekar,
I need more information to help you! 
For example, with which number of warehouses and products did you encounter the error? And what kind of error is it? With which version of Ray? 
Have a great day!

**Comment by aravsekar** [comment]
Hello

Apologies for missing some information. I am testing the same with 2P and 3W and have attached the env settings of the same.  
![Picture1](https://user-images.githubusercontent.com/91839158/195468355-2e1a3306-6504-41c8-98a3-2712c14e35f9.jpg)

I am using the basic Ray version 1.0.0 because this is the only one that my Linux environment accepts. When I initially used Ray version 1.5.2, it gave me the error that is displayed below. Hence after changing that to 1.0.0 I was able to execute the three scenarios. But when I make it more complex with 2P and 3W, with Ray version 1.0.0, it gives me this error 

![Picture2](https://user-images.githubusercontent.com/91839158/195468356-7cfde95a-210b-4f0a-8163-91cf87d553cf.jpg)

Hence the reason I feel that some ray versions are not compatible with certain Linux environments.

**Comment by frenkowski** [comment]
Hi @aravsekar,
I agree that the problem is related to the Ray version given that with version 1.0.0 I also had problems on macOS. 
I suggest you try the latest Ray version available (i.e., [2.0.0](https://github.com/ray-project/ray/releases)).
Let me know if you need any further information!

**Comment by aravsekar** [comment]
Thank you! By any chance can you check the env settings for a 2P and 3W, that I have attached? That will help if I am taking the right path. Please do let me know.

**Comment by frenkowski** [comment]
Hi @aravsekar,
why do you have 6 different arrays for the storage capacities? You should have a number of arrays equal to the number of warehouses (including the factory warehouse), each of which contains a number of elements equal to the number of product types (just like you did for the storage costs).
Have a great day!
