### ISSUE TITLE
Regarding the environment issue with 'ECML-PKDD_SCIMAI-Gym.ipynb'

### ISSUE THREAD

**Issue by ZSZDream** [frenkowski/SCIMAI-Gym#4]
Hello, when I was reproducing the code in 'ECML-PKDD_SCIMAI-Gym.ipynb', after installing the necessary dependencies like ray 1.5.2, I encountered the following error during the reinforcement learning training step：“ERROR services.py:1254 -- Failed to start the dashboard: Failed to read dashbord log: [Errno 2] No such file or directory: 'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\ray\\session_2024-02-20_14-41-15_370942_18176\\logs\\dashboard.log'”.
I suspect that this issue is caused by conflicts between various packages. Could you please provide the 'requirements.txt' file? Thank you. Wishing you all the best.

**Comment by ZSZDream** [comment]
I have made modifications to the code for ECML-PKDD based on the ray 2.3.1 environment in IJPE_SCIMAI-gym.ipynb, and now we can proceed with the experiments.

**Comment by frenkowski** [comment]
Excellent, thank you so much for the update!
